# See: https://github.com/marketplace/actions/renovate-bot-github-action#example
name: Renovate
on:
  schedule:
    # Run everyday 5 a.m
    - cron: '0 5 * * *'
  push:
    branches:
    - main
   
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          configurationFile: ./renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
