# See: https://github.com/marketplace/actions/renovate-bot-github-action#example
name: Renovate
on:
  schedule:
    # Run everyday at 5 a.m
    - cron: '0 5 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: example/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}